* Scripts files
  This repo contains small scripts I have written for various tasks, some still work, some are under development and some I have abandoned.

  The summary of scripts are in following table, you can refer to specific section for full details.
  
  | Script name  | File name       | language | Short description                     |
  | [[Autocomplete]] | autocomplete.py | python   | Autocomplete frequent phrases         |
  | [[Battery Logs]] | battery.py      | Python   | Logs the battery percetage            |
  | [[Conky]]        | conky.sh        | Bash     | Conky start scripts and prerequisites |

* Autocomplete
  /Abandoned project/

  Basically saves a json of phrases you use frequently and then you can use them.

  I'm planning to update this one using Dmenu, with two script options
  - Add new phrase
  - Insert phrase

  I'll probably rewrite it on bash if I do it again.

  
* Battery Logs
  Logs the % of battery you give to it in a file. There is plot_battery.{gnuplot,py} scripts to visualize the logged data.


* Conky
  Script to run the scripts I have on conky directory, as well as to run the necessary scripts before the conky one.

  The file ~daily_for_conky.sh~ is to put into the crontab.
