* Scripts files
  This repo contains small scripts I have written for various tasks, some still work, some are under development and some I have abandoned.

  The summary of scripts are in following table, you can refer to specific section for full details.
  
  | Script Group | File name              | language | Short description                            |
  |--------------+------------------------+----------+----------------------------------------------|
  | Autocomplete | [[./autocomplete.py]]      | python   | Autocomplete frequent phrases                |
  | Battery Logs | [[./battery.py]]           | Python   | Logs the battery percentage                  |
  |              | [[./plot_battery.py]]      | Python   | Plots the battery log                        |
  |              | [[./plot_battery.gnuplot]] | Gnuplot  | Plots the battery log and shows trend        |
  | Conky        | [[./conky.sh]]             | Bash     | Conky start scripts and prerequisites        |
  |              | [[./daily_for_conky.sh]]   | Bash     | Scripts to run daily for conky.              |
  | File Open    | [[./file-open.sh]]         | Bash     | Opens a file with a command.                 |
  | Mail         | [[./mail.py]]              | Python   | Checks for the emails and sends notification |
  |              |                        |          |                                              |

* Autocomplete
  /Abandoned project/

  Basically saves a json of phrases you use frequently and then you can use them.

  I'm planning to update this one using Dmenu, with two script options
  - Add new phrase
  - Insert phrase

  I'll probably rewrite it on bash if I do it again.

  
* Battery Logs
  Logs the % of battery you give to it in a file. There is plot_battery.{gnuplot,py} scripts to visualize the logged data.


* Conky
  Script to run the scripts I have on conky directory, as well as to run the necessary scripts before the conky one.

  The file ~daily_for_conky.sh~ is to put into the crontab.

  
* File Open
  It uses dmenu to open a file, It's basically same as using dmenu to open a program, but the second option will be like a file browser so you can pass that filename as an argument to the program. 


  
* Mail
  It checks the email, sees if there is changes from the saved previous mails. And sends notification if there is a new one. It also prints the text in a colored format for conky.
